export const blogPosts = [
  {
    date: '2026-07-29',
    displayDatePl: '29 Lipca 2026',
    displayDateEn: 'July 29, 2026',
    tagPl: 'Audyt SEO',
    tagEn: 'SEO Audit',
    titlePl: 'Audyt SEO cena 2026 — ile zapłacisz w Polsce?',
    titleEn: 'SEO Audit Price 2026 — How Much Will You Pay in Poland?',
    descPl: 'Sprawdź aktualne cenniki audytów SEO w Polsce na 2026 rok. Ile kosztuje audyt dla małej strony, sklepu e-commerce czy dużego serwisu?',
    descEn: 'Check the current SEO audit pricing in Poland for 2026. How much does an audit cost for a small site, an e-commerce store, or a large website?',
    slug: '/blog/audyt-seo-cena-2026-ile-zaplacisz-w-polsce',
    image: 'https://images.unsplash.com/photo-1579567761406-4684ee0c75b6?auto=format&fit=crop&w=1200&q=80',
    heroImage: 'https://images.unsplash.com/photo-1579567761406-4684ee0c75b6?auto=format&fit=crop&w=1200&q=80'
  },
  {
    date: '2026-07-27',
    displayDatePl: '27 Lipca 2026',
    displayDateEn: 'July 27, 2026',
    tagPl: 'Link Building B2B',
    tagEn: 'B2B Link Building',
    titlePl: 'Link building B2B dla marketerów: strategie i checklista',
    titleEn: 'B2B Link Building for Marketers: Strategies and Checklist',
    descPl: 'Skuteczny link building B2B opiera się na digital PR, partnerstwach i publikacjach eksperckich. Sprawdź, jak to robić.',
    descEn: 'Effective B2B link building is based on digital PR, partnerships, and expert publications. Check how to do it.',
    slug: '/blog/link-building-b2b-dla-marketerow-strategie-i-checklista',
    image: 'https://images.unsplash.com/photo-1620207418302-439b387441b0?auto=format&fit=crop&w=1200&q=80',
    heroImage: 'https://images.unsplash.com/photo-1620207418302-439b387441b0?auto=format&fit=crop&w=1200&q=80'
  },
  {
    date: '2026-07-24',
    displayDatePl: '24 Lipca 2026',
    displayDateEn: 'July 24, 2026',
    tagPl: 'Strategia SEO',
    tagEn: 'SEO Strategy',
    titlePl: 'Dlaczego responsywność i Core Web Vitals to klucz do wyższych pozycji w Google?',
    titleEn: 'Why responsiveness & Core Web Vitals are key to top Google rankings',
    descPl: 'Dowiedz się, jak szybkość ładowania strony i doświadczenie użytkownika przekładają się bezpośrednio na pozycję w wyszukiwarce.',
    descEn: 'Discover how page speed and user experience translate directly into higher organic positioning.',
    slug: '/blog/core-web-vitals-a-pozycje-google',
    image: 'https://images.unsplash.com/photo-1620121692029-d088224ddc74?auto=format&fit=crop&w=1200&q=80'
  },
  {
    date: '2026-07-20',
    displayDatePl: '20 Lipca 2026',
    displayDateEn: 'July 20, 2026',
    tagPl: 'SEO Lokalne',
    tagEn: 'Local SEO',
    titlePl: 'SEO Lokalne dla firm w Warszawie - jak wygrać z konkurencją?',
    titleEn: 'Local SEO for businesses in Warsaw - how to beat the competition?',
    descPl: 'Praktyczny poradnik jak zdominować lokalne wyniki wyszukiwania i zdobyć klientów z Twojej okolicy w Warszawie.',
    descEn: 'A practical guide on how to dominate local search results and get clients from your area in Warsaw.',
    slug: '/blog/seo-lokalne-dla-firm-w-warszawie',
    image: 'https://images.unsplash.com/photo-1604871000636-074fa5117945?auto=format&fit=crop&w=1200&q=80'
  },
  {
    date: '2026-07-28',
    displayDatePl: '28 Lipca 2026',
    displayDateEn: 'July 28, 2026',
    tagPl: 'Budżet SEO',
    tagEn: 'SEO Budget',
    titlePl: 'Ile kosztuje pozycjonowanie w 2026 roku?',
    titleEn: 'How much does SEO cost in 2026?',
    descPl: 'Szczegółowa analiza stawek rynkowych w modelu abonamentowym i success fee dla polskiego rynku B2B.',
    descEn: 'Detailed analysis of market rates in the subscription and success fee models for the Polish B2B market.',
    slug: '/blog/ile-kosztuje-pozycjonowanie-2026',
    image: 'https://images.unsplash.com/photo-1640301998084-c9b80babd03c?auto=format&fit=crop&w=1200&q=80'
  },
  {
    date: '2026-07-28',
    displayDatePl: '28 Lipca 2026',
    displayDateEn: 'July 28, 2026',
    tagPl: 'Budżet SEO',
    tagEn: 'SEO Budget',
    titlePl: 'Ile kosztuje SEO w Polsce? Cennik i pakiety 2026',
    titleEn: 'How much does SEO cost in Poland? Pricing and packages 2026',
    descPl: 'Rozkładamy na czynniki pierwsze ceny pozycjonowania w Polsce. Zobacz, ile kosztuje SEO dla różnych typów firm.',
    descEn: 'We break down the prices of SEO in Poland. See how much SEO costs for different types of businesses.',
    slug: '/blog/ile-kosztuje-seo-w-polsce-cennik-i-pakiety-2026',
    image: 'https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?auto=format&fit=crop&w=1200&q=80'
  }
];
