export const blogPosts = [
  {
    date: '2026-07-31',
    displayDatePl: '31 Lipca 2026',
    displayDateEn: 'July 31, 2026',
    tagPl: 'Google Business',
    tagEn: 'Google Business',
    titlePl: 'Jak skutecznie pozyskiwać opinie w Google? Poradnik',
    titleEn: 'How to effectively get Google reviews? Guide',
    descPl: 'Najskuteczniejsza metoda pozyskiwania opinii Google. Sprawdź, jak zbudować proces, który generuje recenzje.',
    descEn: 'The most effective method of getting Google reviews. Check how to build a process that generates reviews.',
    slug: '/blog/jak-pozyskiwac-opinie-google-poradnik',
    image: '/images/google-reviews-abstract.png',
    heroImage: '/images/google-reviews-abstract.png'
  },
  {
    date: '2026-07-30',
    displayDatePl: '30 Lipca 2026',
    displayDateEn: 'July 30, 2026',
    tagPl: 'Techniczne SEO',
    tagEn: 'Technical SEO',
    titlePl: 'Tag kanoniczny SEO – czym jest, jak działa i jak go wdrożyć w 2026',
    titleEn: 'SEO Canonical Tag – what is it, how it works and how to implement it in 2026',
    descPl: 'Tag kanoniczny (rel=canonical) to fundament SEO. Zobacz, jak unikać duplikacji treści, chronić crawl budget i poprawnie go wdrażać.',
    descEn: 'The canonical tag (rel=canonical) is the foundation of SEO. See how to avoid duplicate content, protect crawl budget, and implement it correctly.',
    slug: '/blog/tag-kanoniczny-seo-jak-wdrozyc-w-2026',
    image: '/images/canonical-tag-seo-cover.png',
    heroImage: '/images/canonical-tag-seo-cover.png'
  },
  {
    date: '2026-07-27',
    displayDatePl: '27 Lipca 2026',
    displayDateEn: 'July 27, 2026',
    tagPl: 'Link Building B2B',
    tagEn: 'B2B Link Building',
    titlePl: 'Link building B2B dla marketerów: strategie i checklista',
    titleEn: 'B2B Link Building for Marketers: Strategies and Checklist',
    descPl: 'Skuteczny link building B2B opiera się na digital PR, partnerstwach i publikacjach eksperckich. Sprawdź, jak to robić.',
    descEn: 'Effective B2B link building is based on digital PR, partnerships, and expert publications. Check how to do it.',
    slug: '/blog/link-building-b2b-dla-marketerow-strategie-i-checklista',
    image: '/images/unsplash-1620207418302-439b387441b0.jpg',
    heroImage: '/images/unsplash-1620207418302-439b387441b0.jpg'
  },
  {
    date: '2026-07-24',
    displayDatePl: '24 Lipca 2026',
    displayDateEn: 'July 24, 2026',
    tagPl: 'Strategia SEO',
    tagEn: 'SEO Strategy',
    titlePl: 'Dlaczego responsywność i Core Web Vitals to klucz do wyższych pozycji w Google?',
    titleEn: 'Why responsiveness & Core Web Vitals are key to top Google rankings',
    descPl: 'Dowiedz się, jak szybkość ładowania strony i doświadczenie użytkownika przekładają się bezpośrednio na pozycję w wyszukiwarce.',
    descEn: 'Discover how page speed and user experience translate directly into higher organic positioning.',
    slug: '/blog/core-web-vitals-a-pozycje-google',
    image: '/images/unsplash-1620121692029-d088224ddc74.jpg'
  },
  {
    date: '2026-07-20',
    displayDatePl: '20 Lipca 2026',
    displayDateEn: 'July 20, 2026',
    tagPl: 'SEO Lokalne',
    tagEn: 'Local SEO',
    titlePl: 'SEO Lokalne dla firm w Warszawie - jak wygrać z konkurencją?',
    titleEn: 'Local SEO for businesses in Warsaw - how to beat the competition?',
    descPl: 'Praktyczny poradnik jak zdominować lokalne wyniki wyszukiwania i zdobyć klientów z Twojej okolicy w Warszawie.',
    descEn: 'A practical guide on how to dominate local search results and get clients from your area in Warsaw.',
    slug: '/blog/seo-lokalne-dla-firm-w-warszawie',
    image: '/images/unsplash-1604871000636-074fa5117945.jpg'
  },
  {
    date: '2026-07-28',
    displayDatePl: '28 Lipca 2026',
    displayDateEn: 'July 28, 2026',
    tagPl: 'Budżet SEO',
    tagEn: 'SEO Budget',
    titlePl: 'Ile kosztuje SEO w Polsce? Cennik i pakiety 2026',
    titleEn: 'How much does SEO cost in Poland? Pricing and packages 2026',
    descPl: 'Rozkładamy na czynniki pierwsze ceny pozycjonowania w Polsce. Zobacz, ile kosztuje SEO dla różnych typów firm.',
    descEn: 'We break down the prices of SEO in Poland. See how much SEO costs for different types of businesses.',
    slug: '/blog/ile-kosztuje-seo-w-polsce-cennik-i-pakiety-2026',
    image: '/images/unsplash-1614850523459-c2f4c699c52e.jpg'
  }
];
